version: '1'

services:
  app:
    image: gitlab.akvelon.net:9444/mikhail.dorodnikov/online-shop
    container_name: app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/OnlineShop
      - SPRING_DATASOURCE_USERNAME=onlineshop
      - SPRING_DATASOURCE_PASSWORD=onlineshop
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE=postgresql
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.PostgreSQL10Dialect

  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=OnlineShop
      - POSTGRES_USER=onlineshop
      - POSTGRES_PASSWORD=onlineshop
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata:
    external: true